alias gs="git status"
alias gc="git commit"
alias gca="git commit -a"
alias gr="git grep"
alias gd='git diff'
alias tree='tree -a -I .git --dirsfirst'
alias w='watchexec --clear --restart -i ".*" -i "*.md" -i Dockerfile --'
alias pull="git pull --rebase"
alias gpp="git pull --rebase && git push"
